data:
  dataset: visl_400
  modality: pose
  subset: cam_1_2_3
  data_dir: ../data/processed/vsl_400
  transform:
    augmentation: True
    aug_prob: 0.7
    add_gaussian_noise: True
    normalization: True
  fps: 30
  debug: False
model:
  arch: spoter
  num_frozen_layers: 0
  num_frames: 70
  hidden_dim: 108
training:
  run_name: spoter_v3.0_multicam
  learning_rate: 0.001
  weight_decay: 0.05
  num_train_epochs: 350
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 256
  dataloader_num_workers: 16
  eval_strategy: epoch
  save_strategy: epoch
  logging_strategy: epoch
  metric_for_best_model: accuracy
  # report_to: wandb
  push_to_hub: False
  # hub_model_id: vsltranslation    # Only enter organization/account name
